- .github/workflows/build.yml
- .gitignore
To make sure we are not breaking stuff
> Build site on PR

- content/en/docs/Creating derivatives/building_gce_images.md
- content/en/docs/Getting started/booting.md
> Add gce image creation

- content/en/docs/Creating derivatives/building_gce_images.md
- content/en/docs/Getting started/booting.md
- layouts/shortcodes/info.html
Adds italics, and a info icon so its more visible that its an extra info
text
> Add info shortcode

- content/en/docs/Creating derivatives/building_azure_images.md
- content/en/docs/Getting started/booting.md
> Add azure image docs

- content/en/docs/Getting started/booting.md
> update the sample user-data for cloud

- layouts/shortcodes/githubembed.html
Allows to import remote github code
> Add githubembed shortcode

- content/en/docs/Reference/cloud_init.md
> Add layout plugin docs in cloud-init

- content/en/docs/Tutorials/trigger_upgrades_with_fleet.md
> Update fleet article

- content/en/docs/Creating derivatives/Packer/build_ami.md
- content/en/docs/Creating derivatives/Packer/build_gcp.md
Related to rancher-sandbox/cOS-toolkit#435
> Add minimal GCP Packer template docs

- content/en/docs/Creating derivatives/build_iso.md
- content/en/docs/Customizing/upgrades.md
- content/en/docs/Examples/creating_bootable_images.md
- content/en/docs/Getting started/_index.md
- content/en/docs/Getting started/booting.md
- content/en/docs/Getting started/download.md
- content/en/docs/Reference/cloud_init.md
- content/en/docs/Tutorials/k3s_and_fleet_on_vanilla_image_example.md
- content/en/docs/_index.md
Fixes: https://github.com/rancher-sandbox/cOS-toolkit/issues/437
> Update repositories, describe released assets and codenames

- content/en/docs/Creating derivatives/Packer/build_ami.md
Part of https://github.com/rancher-sandbox/cOS-toolkit/issues/409
> Add info about temporary sec groups for aws

- content/en/docs/Creating derivatives/Packer/build_ami.md
- content/en/docs/Creating derivatives/Packer/build_azure.md
- content/en/docs/Creating derivatives/Packer/build_gcp.md
Closes https://github.com/rancher-sandbox/cOS-toolkit/issues/474
> Azure docs

- content/en/docs/Getting started/booting.md
This PR adds docs for netboot.
> add docs for netboot

- content/en/docs/Creating derivatives/build_iso.md
Fixes rancher-sandbox/cOS-Toolkit#520
> Document ISO bootloader customization

- content/en/docs/_index.md
> Minor typos

- content/en/docs/Reference/immutable_rootfs.md
- content/en/docs/Tutorials/k3s_and_fleet_on_vanilla_image_example.md
Documentation and example update for rancher-sandbox/cOS-Toolkit#544
Part of rancher-sandbox/cOS-Toolkit#430
> Add persistent state docs

- content/en/docs/Customizing/general_configuration.md
- content/en/docs/Customizing/upgrades.md
Fixes: https://github.com/rancher-sandbox/cOS-toolkit/issues/532
> Add general configuration section

- content/en/docs/Reference/immutable_rootfs.md
Signed-off-by: Kiefer Chang <kiefer.chang@suse.com>
> Fix typo in immutable rootfs section

- content/en/docs/Customizing/stages.md
- content/en/docs/Examples/creating_bootable_images.md
Depends on https://github.com/rancher-sandbox/cOS-toolkit/pull/580
> Describe sentinel files for cloud-init execution

- config.toml
- content/en/docs/Creating derivatives/build_iso.md
- content/en/docs/Creating derivatives/creating_bootable_images.md
- content/en/docs/Customizing/runtime_features.md
- content/en/docs/Reference/immutable_rootfs.md
- content/en/docs/Reference/troubleshooting.md
Enhance docs with a troubleshooting section and few enhancements regarding
the immutable rootfs layout that I've found while working on https://github.com/rancher-sandbox/cOS-toolkit/issues/577.
> Update docs with troubleshooting notes

- content/en/docs/Reference/cloud_init.md
See: https://github.com/rancher-sandbox/cOS-toolkit/issues/618
> Update cloud-init with new supported fields

- config.toml
- content/en/docs/Customizing/configuration_persistency.md
- content/en/docs/Customizing/runtime_persistent_changes.md
- content/en/docs/Customizing/stages.md
- layouts/shortcodes/package.html
Add docs about https://github.com/rancher-sandbox/cOS-toolkit/issues/704 and updates the package-browser URL from https://github.com/rancher-sandbox/cOS-toolkit/issues/714
> Persistent changes runtime

- content/en/docs/Customizing/configure_grub.md
> Add documentation about customizing GRUB menu

- content/en/docs/Getting started/install.md
Documentation for https://github.com/rancher-sandbox/cOS-toolkit/pull/851
> Describe how to install from rescue systems

- content/en/docs/Creating derivatives/build_iso.md
- content/en/docs/Customizing/login.md
- content/en/docs/Customizing/oem_configuration.md
- content/en/docs/Customizing/upgrades.md
- content/en/docs/Development/creating_derivatives.md
- content/en/docs/Getting started/upgrading.md
- content/en/docs/Reference/_index.md
- content/en/docs/Reference/high_level_architecture.md
- content/en/docs/Reference/selinux.md
> Drop references to sample-repo

- content/en/docs/Creating derivatives/build_iso.md
> Use a proper syslinux example

- content/en/docs/Reference/cloud_init.md
Add links to some docs as well as an example.
This should fix https://github.com/rancher-sandbox/cOS-toolkit/issues/1162.
> Add information about templates

- content/en/docs/Reference/cloud_init.md
See https://github.com/rancher-sandbox/cOS-toolkit/issues/1165
> Fixup cloud-init docs growpart samples

- content/en/docs/Getting started/install.md
> Point to the new elemental oci images

- content/en/docs/Creating derivatives/Packer/_index.md
- content/en/docs/Creating derivatives/Packer/build_ami.md
- content/en/docs/Creating derivatives/Packer/build_azure.md
- content/en/docs/Creating derivatives/Packer/build_gcp.md
- content/en/docs/Creating derivatives/creating_bootable_images.md
- content/en/docs/Customizing/stages.md
- content/en/docs/Getting started/booting.md
- content/en/docs/Getting started/deploy.md
- content/en/docs/Tutorials/k3s_and_fleet_on_vanilla_image_example.md
> Drop cos-deploy command usage

- content/en/docs/Creating derivatives/creating_bootable_images.md
Fixes https://github.com/rancher-sandbox/cOS-toolkit/issues/1221
> Add the standard docker example to derivatives exmaples

- content/en/docs/Creating derivatives/build_iso.md
- content/en/docs/Development/creating_derivatives.md
- content/en/docs/Development/dependencies.md
Related to rancher-sandbox/cOS-Toolkit#1217
> Adding elemental's build-iso command docs

- content/en/docs/Development/build_raw_images.md
> Update docs related to build-disk
